- hosts: target2
  vars:
    port_http: 8080
    type: web
    service:
      web:
        name: apache
        rpm: httpd
      db:
        name: mariadb
        rpm: mariadb-server
  tasks:
    - name: installation du logiciel
      debug:
        msg: "Le logiciel {{ service[type]['name'] }} sera installé par le paquet {{
service[type].rpm }}"