- hosts: centos_remote_a
  become: true
  tasks:
  - name: upgrade all packages, excluding kernel
    yum:
      name: '*'
      state: latest
      exclude: kernel*
    when:  ansible_distribution == 'CentOS'