- hosts: target2
  vars:
    port_http: 8080
    service:
      name: apache
      rpm: httpd
  tasks:
    - name: installation du logiciel
      debug:
        msg: "Le logiciel {{ service['name'] }} sera installe par le paquet {{ service.rpm }}"