- hosts: target2
  vars:
    users:
      alice:
        name:  hme
        telephone: 05044303
      bob:
        name:  Bob
        telephone: 0607070606
  tasks:
    - name: user et phone number avec lookup fonction
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"